package com.zdj.miaoshaproject.dataobject;

public class CarRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.uid
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.item_id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.status
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.count
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.uid
     *
     * @return the value of car.uid
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.uid
     *
     * @param uid the value for car.uid
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.item_id
     *
     * @return the value of car.item_id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.item_id
     *
     * @param itemId the value for car.item_id
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.status
     *
     * @return the value of car.status
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.status
     *
     * @param status the value for car.status
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.count
     *
     * @return the value of car.count
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.count
     *
     * @param count the value for car.count
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}