package com.zdj.miaoshaproject.dataobject;

import java.math.BigDecimal;

public class DecreaseLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decrease_log.id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decrease_log.user_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decrease_log.item_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decrease_log.discount
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    private Double discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decrease_log.id
     *
     * @return the value of decrease_log.id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decrease_log.id
     *
     * @param id the value for decrease_log.id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decrease_log.user_id
     *
     * @return the value of decrease_log.user_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decrease_log.user_id
     *
     * @param userId the value for decrease_log.user_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decrease_log.item_id
     *
     * @return the value of decrease_log.item_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decrease_log.item_id
     *
     * @param itemId the value for decrease_log.item_id
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decrease_log.discount
     *
     * @return the value of decrease_log.discount
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public Double getDiscount() {

        BigDecimal b   =   new   BigDecimal(discount);
        double   f1   =   b.setScale(2,   BigDecimal.ROUND_HALF_UP).doubleValue();
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decrease_log.discount
     *
     * @param discount the value for decrease_log.discount
     *
     * @mbg.generated Thu May 27 14:11:06 AWST 2021
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
}