package com.zdj.miaoshaproject.dataobject;

public class ItemImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_detail_img.id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_detail_img.item_id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_detail_img.img_url
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_detail_img.id
     *
     * @return the value of item_detail_img.id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_detail_img.id
     *
     * @param id the value for item_detail_img.id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_detail_img.item_id
     *
     * @return the value of item_detail_img.item_id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_detail_img.item_id
     *
     * @param itemId the value for item_detail_img.item_id
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_detail_img.img_url
     *
     * @return the value of item_detail_img.img_url
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_detail_img.img_url
     *
     * @param imgUrl the value for item_detail_img.img_url
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}