package com.zdj.miaoshaproject.dataobject;

public class OrderDiscountRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_discount_rel.id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_discount_rel.order_id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_discount_rel.discount
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    private Double discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_discount_rel.id
     *
     * @return the value of order_discount_rel.id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_discount_rel.id
     *
     * @param id the value for order_discount_rel.id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_discount_rel.order_id
     *
     * @return the value of order_discount_rel.order_id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_discount_rel.order_id
     *
     * @param orderId the value for order_discount_rel.order_id
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_discount_rel.discount
     *
     * @return the value of order_discount_rel.discount
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_discount_rel.discount
     *
     * @param discount the value for order_discount_rel.discount
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
}