package com.zdj.miaoshaproject.dao;

import com.zdj.miaoshaproject.dataobject.CarRecord;

import java.util.List;

public interface CarRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    int insert(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    int insertSelective(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    CarRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    int updateByPrimaryKeySelective(CarRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Thu May 27 09:58:21 AWST 2021
     */
    int updateByPrimaryKey(CarRecord record);

    List<CarRecord> selectByUserIdItemId(int userId, int itemId);

    int updateByUserIdItemId(int userId, int itemId);

    List<CarRecord> selectByUserId(int userId);
}