package com.zdj.miaoshaproject.dao;

import com.zdj.miaoshaproject.dataobject.FriendDO;

import java.util.List;

public interface FriendDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    int insert(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    int insertSelective(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    FriendDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    int updateByPrimaryKeySelective(FriendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_rel
     *
     * @mbg.generated Thu May 27 10:16:00 AWST 2021
     */
    int updateByPrimaryKey(FriendDO record);

    List<FriendDO> selectByUserId(int userId);

    List<FriendDO> selectByUserIdFriendId(int userId, int friendId);

    List<FriendDO> selectByUserIdItemId(int userId, int itemId);


}