package com.zdj.miaoshaproject.dao;

import com.zdj.miaoshaproject.dataobject.ItemImg;

import java.util.List;

public interface ItemImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int insert(ItemImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int insertSelective(ItemImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    ItemImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int updateByPrimaryKeySelective(ItemImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ItemImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_detail_img
     *
     * @mbg.generated Sat May 08 19:58:41 AWST 2021
     */
    int updateByPrimaryKey(ItemImg record);

    List<ItemImg> selectImgesByItemId(Integer id);
}