package com.zdj.miaoshaproject.dao;

import com.zdj.miaoshaproject.dataobject.OrderDiscountRel;

public interface OrderDiscountRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    int insert(OrderDiscountRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    int insertSelective(OrderDiscountRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    OrderDiscountRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    int updateByPrimaryKeySelective(OrderDiscountRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_discount_rel
     *
     * @mbg.generated Mon Jun 07 14:08:54 AWST 2021
     */
    int updateByPrimaryKey(OrderDiscountRel record);

    OrderDiscountRel selectByOrderId(String orderId);
}